"""Add category and other fields to Product

Revision ID: f56ddaf4813c
Revises: 967b7950d847
Create Date: 2025-07-09 15:35:04.784963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f56ddaf4813c'
down_revision: Union[str, Sequence[str], None] = '967b7950d847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    op.add_column('products', sa.Column('subcategory', sa.String(), nullable=True))
    op.add_column('products', sa.Column('video', sa.String(), nullable=True))
    op.add_column('products', sa.Column('seo_title', sa.String(), nullable=True))
    op.add_column('products', sa.Column('seo_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'seo_description')
    op.drop_column('products', 'seo_title')
    op.drop_column('products', 'video')
    op.drop_column('products', 'subcategory')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
